// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvrP0UAggUQuvd8vFTTtdHxFL0eykANXc',
    appId: '1:421151059964:web:031134a180482cbe1acc79',
    messagingSenderId: '421151059964',
    projectId: 'kaam-wala-546a1',
    authDomain: 'kaam-wala-546a1.firebaseapp.com',
    databaseURL: 'https://kaam-wala-546a1-default-rtdb.firebaseio.com',
    storageBucket: 'kaam-wala-546a1.firebasestorage.app',
    measurementId: 'G-8ZPD55GKVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBalpxypoFrND6o7t90dT1Mol6aft8Yan0',
    appId: '1:421151059964:android:58a1591775f46b221acc79',
    messagingSenderId: '421151059964',
    projectId: 'kaam-wala-546a1',
    databaseURL: 'https://kaam-wala-546a1-default-rtdb.firebaseio.com',
    storageBucket: 'kaam-wala-546a1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvrP0UAggUQuvd8vFTTtdHxFL0eykANXc',
    appId: '1:421151059964:web:5028f08b832f62df1acc79',
    messagingSenderId: '421151059964',
    projectId: 'kaam-wala-546a1',
    authDomain: 'kaam-wala-546a1.firebaseapp.com',
    databaseURL: 'https://kaam-wala-546a1-default-rtdb.firebaseio.com',
    storageBucket: 'kaam-wala-546a1.firebasestorage.app',
    measurementId: 'G-9R4E1JTL09',
  );
}
